<?php

namespace AppBundle\Repository;

/**
 * OrgRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrgRepository extends \Doctrine\ORM\EntityRepository
{
}
