<?php

namespace AppBundle\Repository;

/**
 * TenantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TenantRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return array
     */
    public function findOneBySchema($schema)
    {
        return $this->getEntityManager()
            ->createQuery("SELECT t FROM AppBundle:Tenant t WHERE dbSchema = '{$schema}'")
            ->getResult();
    }
}
